### ISSUE TITLE
Update sparkpost to 2.0

### ISSUE THREAD

**Issue by kim-dongit** [wvdongen/cakephp-sparkpost#4]
See https://github.com/SparkPost/php-sparkpost/blob/master/MIGRATION.md and do not forget to change the composer entry to sparkpost/sparkpost, besides it version. I.e.:
"sparkpost/php-sparkpost": "~1.0",
becomes:
"sparkpost/sparkpost": "~2.0".

**Comment by wvdongen** [comment]
Done. Please upgrade your cake mail config
